# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
