# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='profile',
            name='EUR',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='USD',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
