# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20180312_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='unseen', max_length=30),
        ),
    ]
