# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='home_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='target_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
