# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_completeorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='home_backup',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='target_backup',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
