# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_profile_default_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
