# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20180305_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='EUR',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='USD',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
