# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20180305_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RON',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
