# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_card_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='currency',
            new_name='c_currency',
        ),
    ]
