# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0014_auto_20180317_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=140, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date_seen', models.DateField(blank=True, null=True)),
                ('time_seen', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='sending', max_length=10)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
