# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_back',
            field=models.CharField(default='sending', max_length=10),
        ),
    ]
