# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_message_status_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_final',
            field=models.CharField(default='sending', max_length=10),
        ),
    ]
