# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseditem',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
