# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_ophistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophistory',
            name='optype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ophistory',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
