# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20180402_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophistory',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ophistory',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
