# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
